# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bitgn import harness_pb2 as bitgn_dot_harness__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bitgn/harness_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HarnessServiceStub(object):
    """HarnessService is the primary entrypoint into the BitGN Benchmarks platform.
    Most methods require authentication with BitGN platform API key
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/bitgn.harness.HarnessService/Status',
                request_serializer=bitgn_dot_harness__pb2.StatusRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetBenchmark = channel.unary_unary(
                '/bitgn.harness.HarnessService/GetBenchmark',
                request_serializer=bitgn_dot_harness__pb2.GetBenchmarkRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.GetBenchmarkResponse.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/bitgn.harness.HarnessService/StartRun',
                request_serializer=bitgn_dot_harness__pb2.StartRunRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.StartRunResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/bitgn.harness.HarnessService/GetRun',
                request_serializer=bitgn_dot_harness__pb2.GetRunRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.SubmitRun = channel.unary_unary(
                '/bitgn.harness.HarnessService/SubmitRun',
                request_serializer=bitgn_dot_harness__pb2.SubmitRunRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.SubmitRunResponse.FromString,
                _registered_method=True)
        self.StartPlayground = channel.unary_unary(
                '/bitgn.harness.HarnessService/StartPlayground',
                request_serializer=bitgn_dot_harness__pb2.StartPlaygroundRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.StartPlaygroundResponse.FromString,
                _registered_method=True)
        self.StartTrial = channel.unary_unary(
                '/bitgn.harness.HarnessService/StartTrial',
                request_serializer=bitgn_dot_harness__pb2.StartTrialRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.StartTrialResponse.FromString,
                _registered_method=True)
        self.GetTrial = channel.unary_unary(
                '/bitgn.harness.HarnessService/GetTrial',
                request_serializer=bitgn_dot_harness__pb2.GetTrialRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.GetTrialResponse.FromString,
                _registered_method=True)
        self.EndTrial = channel.unary_unary(
                '/bitgn.harness.HarnessService/EndTrial',
                request_serializer=bitgn_dot_harness__pb2.EndTrialRequest.SerializeToString,
                response_deserializer=bitgn_dot_harness__pb2.EndTrialResponse.FromString,
                _registered_method=True)


class HarnessServiceServicer(object):
    """HarnessService is the primary entrypoint into the BitGN Benchmarks platform.
    Most methods require authentication with BitGN platform API key
    """

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBenchmark(self, request, context):
        """Fetch information about a given benchmark
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Starting a leaderboard run will prepopulate trial parameters from the benchmark
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPlayground(self, request, context):
        """Start an isolated ad-hoc trial that is not attached to a leaderboard run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrial(self, request, context):
        """Start a prepared trial whose seed and metadata were fixed earlier by the platform (by starting a run).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrial(self, request, context):
        """Get current state of the trial
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndTrial(self, request, context):
        """End trial. For Open benchmarks this will trigger evaluation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=bitgn_dot_harness__pb2.StatusRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.StatusResponse.SerializeToString,
            ),
            'GetBenchmark': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBenchmark,
                    request_deserializer=bitgn_dot_harness__pb2.GetBenchmarkRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.GetBenchmarkResponse.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=bitgn_dot_harness__pb2.StartRunRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.StartRunResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=bitgn_dot_harness__pb2.GetRunRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.GetRunResponse.SerializeToString,
            ),
            'SubmitRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRun,
                    request_deserializer=bitgn_dot_harness__pb2.SubmitRunRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.SubmitRunResponse.SerializeToString,
            ),
            'StartPlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPlayground,
                    request_deserializer=bitgn_dot_harness__pb2.StartPlaygroundRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.StartPlaygroundResponse.SerializeToString,
            ),
            'StartTrial': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrial,
                    request_deserializer=bitgn_dot_harness__pb2.StartTrialRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.StartTrialResponse.SerializeToString,
            ),
            'GetTrial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrial,
                    request_deserializer=bitgn_dot_harness__pb2.GetTrialRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.GetTrialResponse.SerializeToString,
            ),
            'EndTrial': grpc.unary_unary_rpc_method_handler(
                    servicer.EndTrial,
                    request_deserializer=bitgn_dot_harness__pb2.EndTrialRequest.FromString,
                    response_serializer=bitgn_dot_harness__pb2.EndTrialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bitgn.harness.HarnessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bitgn.harness.HarnessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HarnessService(object):
    """HarnessService is the primary entrypoint into the BitGN Benchmarks platform.
    Most methods require authentication with BitGN platform API key
    """

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/Status',
            bitgn_dot_harness__pb2.StatusRequest.SerializeToString,
            bitgn_dot_harness__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBenchmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/GetBenchmark',
            bitgn_dot_harness__pb2.GetBenchmarkRequest.SerializeToString,
            bitgn_dot_harness__pb2.GetBenchmarkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/StartRun',
            bitgn_dot_harness__pb2.StartRunRequest.SerializeToString,
            bitgn_dot_harness__pb2.StartRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/GetRun',
            bitgn_dot_harness__pb2.GetRunRequest.SerializeToString,
            bitgn_dot_harness__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/SubmitRun',
            bitgn_dot_harness__pb2.SubmitRunRequest.SerializeToString,
            bitgn_dot_harness__pb2.SubmitRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/StartPlayground',
            bitgn_dot_harness__pb2.StartPlaygroundRequest.SerializeToString,
            bitgn_dot_harness__pb2.StartPlaygroundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTrial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/StartTrial',
            bitgn_dot_harness__pb2.StartTrialRequest.SerializeToString,
            bitgn_dot_harness__pb2.StartTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/GetTrial',
            bitgn_dot_harness__pb2.GetTrialRequest.SerializeToString,
            bitgn_dot_harness__pb2.GetTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndTrial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.harness.HarnessService/EndTrial',
            bitgn_dot_harness__pb2.EndTrialRequest.SerializeToString,
            bitgn_dot_harness__pb2.EndTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
