# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bitgn.vm import pcm_pb2 as bitgn_dot_vm_dot_pcm__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bitgn/vm/pcm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PcmRuntimeStub(object):
    """buf:lint:ignore SERVICE_SUFFIX
    service for the PCM runtime
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Read',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.ReadRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Write',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.WriteRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Delete',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.DeleteRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.MkDir = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/MkDir',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.MkDirRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.MkDirResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Move',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.MoveRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/List',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.ListRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Tree = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Tree',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.TreeRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.TreeResponse.FromString,
                _registered_method=True)
        self.Find = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Find',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.FindRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.FindResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Search',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.SearchRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Context = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Context',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.ContextRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.Answer = channel.unary_unary(
                '/bitgn.vm.pcm.PcmRuntime/Answer',
                request_serializer=bitgn_dot_vm_dot_pcm__pb2.AnswerRequest.SerializeToString,
                response_deserializer=bitgn_dot_vm_dot_pcm__pb2.AnswerResponse.FromString,
                _registered_method=True)


class PcmRuntimeServicer(object):
    """buf:lint:ignore SERVICE_SUFFIX
    service for the PCM runtime
    """

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MkDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Context(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PcmRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.ReadRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.WriteRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.WriteResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.DeleteRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.DeleteResponse.SerializeToString,
            ),
            'MkDir': grpc.unary_unary_rpc_method_handler(
                    servicer.MkDir,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.MkDirRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.MkDirResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.MoveRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.MoveResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.ListRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.ListResponse.SerializeToString,
            ),
            'Tree': grpc.unary_unary_rpc_method_handler(
                    servicer.Tree,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.TreeRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.TreeResponse.SerializeToString,
            ),
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.FindRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.FindResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.SearchRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.SearchResponse.SerializeToString,
            ),
            'Context': grpc.unary_unary_rpc_method_handler(
                    servicer.Context,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.ContextRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.ContextResponse.SerializeToString,
            ),
            'Answer': grpc.unary_unary_rpc_method_handler(
                    servicer.Answer,
                    request_deserializer=bitgn_dot_vm_dot_pcm__pb2.AnswerRequest.FromString,
                    response_serializer=bitgn_dot_vm_dot_pcm__pb2.AnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bitgn.vm.pcm.PcmRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bitgn.vm.pcm.PcmRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PcmRuntime(object):
    """buf:lint:ignore SERVICE_SUFFIX
    service for the PCM runtime
    """

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Read',
            bitgn_dot_vm_dot_pcm__pb2.ReadRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Write',
            bitgn_dot_vm_dot_pcm__pb2.WriteRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Delete',
            bitgn_dot_vm_dot_pcm__pb2.DeleteRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MkDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/MkDir',
            bitgn_dot_vm_dot_pcm__pb2.MkDirRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.MkDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Move',
            bitgn_dot_vm_dot_pcm__pb2.MoveRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/List',
            bitgn_dot_vm_dot_pcm__pb2.ListRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Tree',
            bitgn_dot_vm_dot_pcm__pb2.TreeRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.TreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Find',
            bitgn_dot_vm_dot_pcm__pb2.FindRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.FindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Search',
            bitgn_dot_vm_dot_pcm__pb2.SearchRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Context(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Context',
            bitgn_dot_vm_dot_pcm__pb2.ContextRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bitgn.vm.pcm.PcmRuntime/Answer',
            bitgn_dot_vm_dot_pcm__pb2.AnswerRequest.SerializeToString,
            bitgn_dot_vm_dot_pcm__pb2.AnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
